In [94]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [95]:
df = pd.read_csv(r"D:\Arcap\Data_Cleaning_Tasks\zomato.csv", encoding='latin1')  # encoding changed to handle special characters
df_copy = df.copy()
print("shape", df_copy.shape)

shape (9551, 21)

In [96]:
df_copy = df.copy()
df_copy.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [97]:
# 1. Handling Missing Values
print("\nMissing values per column before cleaning:")
print(df_copy.isnull().sum())

Missing values per column before cleaning:
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [98]:
# - Drop rows where 'Cuisines' is missing
df_copy = df_copy.dropna(subset=['Cuisines'])

In [99]:
# If needed, fill numeric columns with median (example: 'Average Cost for two')
df_copy['Average Cost for two'] = df_copy['Average Cost for two'].fillna(df_copy['Average Cost for two'].median())

In [100]:
print("\nMissing values after cleaning:")
print(df_copy.isnull().sum())

Missing values after cleaning:
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [101]:
#2 . Removing Duplicates
duplicates = df_copy.duplicated().sum() # Checks for duplicates
print("\nNumber of duplicate rows:", duplicates)
print("shape", df_copy.shape)

Number of duplicate rows: 0
shape (9542, 21)

In [102]:
df_copy = df_copy.drop_duplicates() # Drops if any duplicate rows
print("shape", df_copy.shape)

shape (9542, 21)

In [103]:
#3(4) String Cleaning & Standardization
#Strip spaces and standardize text columns
string_cols = ['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose', 'Cuisines', 'Currency']
for col in string_cols:
    df_copy[col] = df_copy[col].str.strip() # Removes extra spaces.
    df_copy[col] = df_copy[col].str.title()  # Capitalize each word

In [104]:
#4 (9) Data Type Conversion And Validation
numeric_cols = ['Restaurant ID', 'Country Code', 'Longitude', 'Latitude', 
                'Average Cost for two', 'Price range', 'Aggregate rating', 'Votes']

for col in numeric_cols:
    df_copy[col] = pd.to_numeric(df_copy[col], errors='coerce')   #converts the column to a numeric type (int or float).

print("\nData types after conversion:")    # Displays the data type of each column after conversion.
print(df_copy.dtypes)   #all numeric columns are now int64 or float64
print("shape", df_copy.shape)

Data types after conversion:
Restaurant ID             int64
Restaurant Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
Longitude               float64
Latitude                float64
Cuisines                 object
Average Cost for two      int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
dtype: object
shape (9542, 21)

In [105]:
before_shape = df_copy.shape[0]
print("Shape before outliers removal:",before_shape)
Q1 = df_copy['Average Cost for two'].quantile(0.25)
Q3 = df_copy['Average Cost for two'].quantile(0.75)
IQR = Q3 - Q1

df_copy = df_copy[(df_copy['Average Cost for two'] >= Q1 - 1.5*IQR) & (df_copy['Average Cost for two'] <= Q3 + 1.5*IQR)]
after_shape = df_copy.shape[0]
print("No. of Outliers detected:", before_shape - after_shape)
after = print("shape after removing outliers:", after_shape)

Shape before outliers removal: 9542
No. of Outliers detected: 853
shape after removing outliers: 8689

In [106]:
#6(7): Encode Categorical Variables 
df_copy['Has Table booking'] = df_copy['Has Table booking'].map({'Yes':1, 'No':0})
df_copy['Has Online delivery'] = df_copy['Has Online delivery'].map({'Yes':1, 'No':0})
df_copy.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,No,No,3,4.5,Dark Green,Excellent,591
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, Sm Megamall, ...","Sm Megamall, Ortigas, Mandaluyong City","Sm Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),0,0,No,No,3,4.4,Green,Very Good,336
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,532
10,6309903,Silantro Fil-Mex,162,Pasig City,"75 East Capitol Drive, Kapitolyo, Pasig City",Kapitolyo,"Kapitolyo, Pasig City",121.057916,14.567689,"Filipino, Mexican",...,Botswana Pula(P),0,0,No,No,3,4.9,Dark Green,Excellent,1070

In [110]:
#7(8) Scaling / Normalization 
# converts Rating value between 0 and 1

# Create scaler
scaler = MinMaxScaler()

# Apply scaling to 'Aggregate rating'
df_copy['Votes'] = scaler.fit_transform(df_copy[['Votes']])
df_copy.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,0.032482
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,No,No,3,4.5,Dark Green,Excellent,0.061136
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, Sm Megamall, ...","Sm Megamall, Ortigas, Mandaluyong City","Sm Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),0,0,No,No,3,4.4,Green,Very Good,0.034757
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,0.055033
10,6309903,Silantro Fil-Mex,162,Pasig City,"75 East Capitol Drive, Kapitolyo, Pasig City",Kapitolyo,"Kapitolyo, Pasig City",121.057916,14.567689,"Filipino, Mexican",...,Botswana Pula(P),0,0,No,No,3,4.9,Dark Green,Excellent,0.110686

In [108]:
# Step 9: Final Check
# -------------------------------
print("\nFinal dataset info:")
print(df_copy.info())

Final dataset info:
<class 'pandas.core.frame.DataFrame'>
Index: 8689 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         8689 non-null   int64
 1   Restaurant Name       8689 non-null   object
 2   Country Code          8689 non-null   int64
 3   City                  8689 non-null   object
 4   Address               8689 non-null   object
 5   Locality              8689 non-null   object
 6   Locality Verbose      8689 non-null   object
 7   Longitude             8689 non-null   float64
 8   Latitude              8689 non-null   float64
 9   Cuisines              8689 non-null   object
 10  Average Cost for two  8689 non-null   int64
 11  Currency              8689 non-null   object
 12  Has Table booking     8689 non-null   int64
 13  Has Online delivery   8689 non-null   int64
 14  Is delivering now     8689 non-null   object
 15  Switch to order menu  8689 non-null   object
 16  Price range           8689 non-null   int64
 17  Aggregate rating      8689 non-null   float64
 18  Rating color          8689 non-null   object
 19  Rating text           8689 non-null   object
 20  Votes                 8689 non-null   float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.5+ MB
None